# D2PFuzz Stress Testing Configuration Example
# Suitable for: Performance testing, stress testing, load validation

server:
  host: "localhost"
  port: 8080
  timeout: 60

mode: "fuzz"

tx_fuzz:
  enabled: true
  chain_id: 3151908
  max_gas_price: 20000000000
  max_gas_limit: 8000000
  tx_per_second: 100
  fuzz_duration_sec: 300
  seed: 0
  use_accounts: true
  load_pattern_type: "constant"
  max_concurrent_tx: 500
  max_retries: 5
  retry_delay: 500ms
  circuit_breaker: true
  failure_threshold: 10
  rpc_endpoints:
    - "http://172.16.0.11:8545"
    - "http://172.16.0.12:8545"  # Multiple RPC endpoints for improved reliability

p2p:
  enabled: false  # Recommended to disable P2P during stress testing to focus on transaction performance

fuzzing:
  enabled: true
  max_iterations: 1000
  mutation_rate: 0.2
  seed: 12345
  protocols:
    - "eth"

monitoring:
  enabled: true
  log_level: "warn"  # Reduce log output to improve performance
  metrics_port: 9090
  report_interval: 30
  stats_interval_sec: 10

output:
  directory: "./stress_output"
  format: "json"
  compress: true
  include_details: false  # Reduce output details to improve performance

log:
  directory: "./stress_logs"
  template: "stress"
  auto_generate: true
  include_details: false

accounts:
  - address: "0x8943545177806ED17B9F23F0a21ee5948eCaa776"
    private_key: "bcdf20249abf0ed6d944c0288fad489e33f66b3960d9e6229c1cd214ed3bbe31"
  - address: "0xE25583099BA105D9ec0A67f5Ae86D90e50036425"
    private_key: "39725efee3fb28614de3bacaffe4cc4bd8c8436257e2c8bb887c4b5c4be45e76d"
  - address: "0x6951b5Bd815043E3F842c1b026b0Fa888Cc2DD85"
    private_key: "53321db7c1e331d93a11a41d16f004d7ff63972ec8ec7c25db329728ceeb1710"
  - address: "0xd9145CCE52D386f254917e481eB44e9943F39138"
    private_key: "ab63b23eb7941c1251757e24b3d2350d2bc05c3c388d06f8fe6feafefb1e8c70"